[tool.black]
line-length = 100
target-version = ['py36', "py37", "py38",]
experimental_string_processing = true
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |\.tox
  |Dockerfile
  |Jenkinfile
  | _build
  | dist
)/
'''

[tool.isort]
profile = 'black'
multi_line_output = 3
